api_id: 2571243     
api_hash: '31e2b3ab0e54ea431358ca57da209640' 
session_name: 'forwardgram' 

# The channel names that you'd like to forward messages from.
# The user running the client must have these channels present on it's dialogs.
input_channel_ids:
  -'Saleesh Oneclick'
 
  

# The output channel names that the messages will be forwarded to.
# The user running the client must have a write access to those channels, and have the channels present on theirs dialogs.
output_channel_names: 
  -'Hi'
  -'Check'
  -'Kerala IT Jobs'
  
  
